### ISSUE TITLE
Issue: Issue of data display for merged cells in spreadsheet.

### ISSUE THREAD

**Issue by jiteshjosh** [mogsdad/SheetConverter#1]
## Description of issue
When cells are merged in spreadsheet it doesn't display it correctly on mail body. It display all such data in first column.

## Cell Format exhibiting problem
Data should be displayed in same place where it displayed in spreadsheet for merged cells.

## Expected result vs Observed result
Data should be displayed in same place where it displayed in spreadsheet for merged cells.

## Installed Library Version

5

**Comment by mogsdad** [comment]
That's the 5th point in the "Caveats" list. Known, and unable to support via Google Apps Script at this time.

**Comment by smsuresh** [comment]
Please fix this , Will be really helpful.
