### ISSUE TITLE
Issue: HTML does not maintain duration over 24 hours

### ISSUE THREAD

**Issue by samlappage** [mogsdad/SheetConverter#13]
## Description of issue
When sending an email using the HTML converter, cells with a duration over 24 hours are reduced to a time format h:mm:ss 

## Cell Format exhibiting problem
"[h]:mm:ss"

## Expected result vs Observed result
37:05:24 shows as 13:05:24

## Installed Library Version
6

**Comment by mogsdad** [comment]
https://github.com/mogsdad/SheetConverter/pull/14
