### ISSUE TITLE
V8 support

### ISSUE THREAD

**Issue by abkarino** [mogsdad/SheetConverter#15]
https://github.com/mogsdad/SheetConverter/blob/master/SheetConverter/Code.gs#L58
`class` keyword is reserved, you should rename it.

**Comment by aminco-edw** [comment]
Yes, please fix. This kicks up an error with GAS V8 turned on.

**Comment by sai-creator** [comment]
The error I am getting is "SyntaxError: Unexpected token class (line 57, file "Code", project "SheetConverter")".

So I have disabled Chrome V8 for now. Kindly make required changes in the code.

**Comment by jmklee** [comment]
> The error I am getting is "SyntaxError: Unexpected token class (line 57, file "Code", project "SheetConverter")".
> 
> So I have disabled Chrome V8 for now. Kindly make required changes in the code.

That happen to me what should i do?

**Comment by sai-creator** [comment]
> > The error I am getting is "SyntaxError: Unexpected token class (line 57, file "Code", project "SheetConverter")".
> > So I have disabled Chrome V8 for now. Kindly make required changes in the code.
> 
> That happen to me what should i do?

I disabled Chrome V8 and it worked fine.

**Comment by mogsdad** [comment]
https://github.com/mogsdad/SheetConverter/pull/16

**Comment by j6274** [comment]
was this update made? I am still getting this error message. or please advise how to disable Chrome V8. Thanks!
