### ISSUE TITLE
Issue: PM hour value stays in 24hr format

### ISSUE THREAD

**Issue by andrewdimech** [mogsdad/SheetConverter#3]
## Description of issue

Logger.log(SheetConverter.convertCell(new Date('Sun Oct 25 2015 14:10:58 GMT+0200 (CEST)'), "h:mm am/pm"));
    // Bug: Returns 13:10 PM instead of 1:10 PM
## Installed Library Version

Latest

Can you give an indication as to by  when will you be able to fix the issue?

**Comment by mogsdad** [comment]
https://github.com/mogsdad/SheetConverter/pull/14
