### ISSUE TITLE
Issue: Merged cells do not convert correctly

### ISSUE THREAD

**Issue by hdemirev** [mogsdad/SheetConverter#7]
## Description of issue
If merged cells are present in sheet, all text gets pushed to first cell

## Cell Format exhibiting problem
Merged cells

## Expected result vs Observed result
Expect to see result as merged cell

## Installed Library Version
6

**Comment by comscience15** [comment]
yeah i see it too. Are you going to fix it??

**Comment by mogsdad** [comment]
I'm happy to take merge requests, if anyone wants to provide a fix.

**Comment by poetrykungfu** [comment]
I'm very new to all of this but is there not a way of using getColSpan and getRowSpan to check which cells are merged and which are not?

**Comment by aignato** [comment]
Has anyone implemented a successful fix for this issue?

**Comment by CamilleNilles** [comment]
Do you have updates on this? Or do you have any suggestion ?

**Comment by DeFlanko** [comment]
Checking in on the progress of this.

**Comment by mogsdad** [comment]
https://github.com/mogsdad/SheetConverter/pull/12
