### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by Vinzzou** [mogsdad/SheetConverter#8]
## Description of issue
when using the convertRange2html functiun, and tryng to send the html code by email then, the result does not correspond to what we see in googleSheet

## Cell Format exhibiting problem
There are problems on : 
- Cell borders 
- Return to line in clumne
- Cell mergin

## Expected result vs Observed result
here is was I am expecting
![image](https://user-images.githubusercontent.com/24964640/28912362-3f30eefc-7834-11e7-816b-c63c5213bbb0.png)

here is what I get in email : 
![image](https://user-images.githubusercontent.com/24964640/28912393-5d6609b6-7834-11e7-8c1c-f57357a46c98.png)

## Installed Library Version
V6, last version I think

**Comment by mogsdad** [comment]
Refer to caveat #2. https://github.com/mogsdad/SheetConverter/blob/master/README.md
